// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpxNzJ0dXeZfkJLyPFAHKveIOdZKjM_sA',
    appId: '1:762008277366:web:4684d8c2c6746f9037aa57',
    messagingSenderId: '762008277366',
    projectId: 'kmgapp-fd7b1',
    authDomain: 'kmgapp-fd7b1.firebaseapp.com',
    storageBucket: 'kmgapp-fd7b1.firebasestorage.app',
    measurementId: 'G-QM81DD9QS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb8-MnxidLlZMfn8aKT7gcW3lfbGYH6ds',
    appId: '1:762008277366:android:044fafccc10cafdc37aa57',
    messagingSenderId: '762008277366',
    projectId: 'kmgapp-fd7b1',
    storageBucket: 'kmgapp-fd7b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu1GgjBarRMIzZM_i7QFH8Qxhplj3H-aU',
    appId: '1:762008277366:ios:5a02739b86b49bd437aa57',
    messagingSenderId: '762008277366',
    projectId: 'kmgapp-fd7b1',
    storageBucket: 'kmgapp-fd7b1.firebasestorage.app',
    iosBundleId: 'com.example.kmg',
  );
}
